basePath: /
host: localhost:8080
info:
  contact:
    name: GLNG-KS07 - Group 5
    url: https://github.com/yusrililhm/group-5-final-project-2-mygram-app
  description: Final Project 2 Kampus Merdeka
  title: MyGram App
  version: "1.0"
paths: {}
swagger: "2.0"
